## Documentation: http://docs.travis-ci.com/user/languages/julia/

# Need sudo to run docker
sudo: required
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly

# Since we're testing the Docker API, we need to add Docker as a dependency to the CI build
services:
  - docker

notifications:
  email: false

git:
  depth: 1

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment following lines to deploy documentation
# jobs:
#   include:
#     - stage: Documentation
#       julia: 1.0
#       os: linux
#       script:
#         - julia --project=docs -e 'using Pkg; Pkg.instantiate()'
#         - julia --project=docs --color=yes docs/make.jl
#       after_success: skip

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
